services:
  - type: web
    name: mmi-scanner-server
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NIFTY50_POLL_INTERVAL
        value: "10000"
      - key: NIFTY500_POLL_INTERVAL
        value: "10000"
